name: Security and Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: "0 9 * * 1"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install safety bandit

      - name: Run safety check for known vulnerabilities
        run: |
          safety check

      - name: Run bandit security linter
        run: |
          bandit -r src/ -f json -o bandit-report.json || true
          bandit -r src/

      - name: Upload bandit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-report
          path: bandit-report.json

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pip-audit

      - name: Audit dependencies
        run: |
          pip-audit --desc

      - name: Check for outdated packages
        run: |
          pip list --outdated

  test-import-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Test import time
        run: |
          python -c "import time; start = time.time(); import wyrdbound_dice; print(f'Import time: {time.time() - start:.4f}s')"

      - name: Test basic functionality
        run: |
          python -c "
          from wyrdbound_dice import Dice
          import time

          # Test basic rolls
          start = time.time()
          for _ in range(1000):
              result = Dice.roll('1d20')
          print(f'1000 basic rolls took: {time.time() - start:.4f}s')

          # Test complex rolls
          start = time.time()
          for _ in range(100):
              result = Dice.roll('4d6kh3 + 2d8 - 1d4')
          print(f'100 complex rolls took: {time.time() - start:.4f}s')
          "
